### ISSUE TITLE
Dont load 

### ISSUE THREAD

**Issue by UnEnanoMas** [JavierLeon9966/Alias#1]
07.04 15:31:42 [Server] Server thread/INFO Enabling Alias v1.0.1
07.04 15:31:42 [Server] Server thread/CRITICAL Error: "Class 'poggit\libasynql\libasynql' not found" (EXCEPTION) in "plugins/Alias-13b8a6335e1e00400139045be256a3545006a9c7/src/JavierLeon9966/Alias/Alias" at line 39
07.04 15:31:42 [Server] Server thread/CRITICAL #0 pmsrc/src/pocketmine/plugin/PluginBase(116): JavierLeon9966\Alias\Alias->onEnable()
07.04 15:31:42 [Server] Server thread/CRITICAL #1 pmsrc/src/pocketmine/plugin/PluginManager(552): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
07.04 15:31:42 [Server] Server thread/CRITICAL #2 pmsrc/src/pocketmine/Server(1785): pocketmine\plugin\PluginManager->enablePlugin(object JavierLeon9966\Alias\Alias)
07.04 15:31:42 [Server] Server thread/CRITICAL #3 pmsrc/src/pocketmine/Server(1771): pocketmine\Server->enablePlugin(object JavierLeon9966\Alias\Alias)
07.04 15:31:42 [Server] Server thread/CRITICAL #4 pmsrc/src/pocketmine/Server(1584): pocketmine\Server->enablePlugins(integer 1)
07.04 15:31:42 [Server] Server thread/CRITICAL #5 pmsrc/src/pocketmine/PocketMine(291): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[48] /, string[56] /plugins/)
07.04 15:31:42 [Server] Server thread/CRITICAL #6 pmsrc/src/pocketmine/PocketMine(321): pocketmine\server()
07.04 15:31:42 [Server] Server thread/CRITICAL #7 pmsrc(11): require(string[108] phar:///PMMP-Latest-Stable.phar/s)
07.04 15:31:42 [Server] Server thread/INFO Disabling Alias v1.0.1

(Alias lat ver)
(libasynql dev 139)

**Comment by UnEnanoMas** [comment]
07.04 15:38:44 [Server] Server thread/CRITICAL ErrorException: "Undefined index: Data" (EXCEPTION) in "plugins/Alias-13b8a6335e1e00400139045be256a3545006a9c7/src/JavierLeon9966/Alias/Alias" at line 63
07.04 15:38:44 [Server] Server thread/CRITICAL #0 plugins/Alias-13b8a6335e1e00400139045be256a3545006a9c7/src/JavierLeon9966/Alias/Alias(63): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string[21] Undefined index: Data, string[137] /plugins/Alias-13b8a6335e1e004001, integer 63, array[2])
07.04 15:38:44 [Server] Server thread/CRITICAL #1 /virions/libasynql_dev-137 (2).phar/src/poggit/libasynql/base/DataConnectorImpl(159): JavierLeon9966\Alias\Alias->JavierLeon9966\Alias\{closure}(array[0], array[0])
07.04 15:38:44 [Server] Server thread/CRITICAL #2 /virions/libasynql_dev-137 (2).phar/src/poggit/libasynql/base/DataConnectorImpl(189): poggit\libasynql\base\DataConnectorImpl->poggit\libasynql\base\{closure}(object poggit\libasynql\result\SqlSelectResult)
07.04 15:38:44 [Server] Server thread/CRITICAL #3 /virions/libasynql_dev-137 (2).phar/src/poggit/libasynql/base/SqlThreadPool(112): poggit\libasynql\base\DataConnectorImpl->poggit\libasynql\base\{closure}(object poggit\libasynql\result\SqlSelectResult)
07.04 15:38:44 [Server] Server thread/CRITICAL #4 /virions/libasynql_dev-137 (2).phar/src/poggit/libasynql/base/DataConnectorImpl(268): poggit\libasynql\base\SqlThreadPool->readResults(array[1])
07.04 15:38:44 [Server] Server thread/CRITICAL #5 /virions/libasynql_dev-137 (2).phar/src/poggit/libasynql/base/SqlThreadPool(65): poggit\libasynql\base\DataConnectorImpl->checkResults()
07.04 15:38:44 [Server] Server thread/CRITICAL #6 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(113): poggit\libasynql\base\SqlThreadPool->poggit\libasynql\base\{closure}()
07.04 15:38:44 [Server] Server thread/CRITICAL #7 (): --- below is the original stack trace ---()
07.04 15:38:44 [Server] Server thread/CRITICAL #8 /virions/libasynql_dev-137 (2).phar/src/poggit/libasynql/base/DataConnectorImpl(178): poggit\libasynql\base\DataConnectorImpl->executeImplRaw(string[50] SELECT Data.FROM Players.WHERE Username=:username;, array[0], integer 3, object Closure, NULL )
07.04 15:38:44 [Server] Server thread/CRITICAL #9 /virions/libasynql_dev-137 (2).phar/src/poggit/libasynql/base/DataConnectorImpl(157): poggit\libasynql\base\DataConnectorImpl->executeImpl(string[12] alias.search, array[1], integer 3, object Closure, NULL )
07.04 15:38:44 [Server] Server thread/CRITICAL #10 plugins/Alias-13b8a6335e1e00400139045be256a3545006a9c7/src/JavierLeon9966/Alias/Alias(67): poggit\libasynql\base\DataConnectorImpl->executeSelect(string[12] alias.search, array[1], object Closure)
07.04 15:38:44 [Server] Server thread/CRITICAL #11 plugins/Alias-13b8a6335e1e00400139045be256a3545006a9c7/src/JavierLeon9966/Alias/Alias(117): JavierLeon9966\Alias\Alias->saveDatabase(string[10] UnEnanoMas)
07.04 15:38:44 [Server] Server thread/CRITICAL #12 pmsrc/src/pocketmine/plugin/MethodEventExecutor(42): JavierLeon9966\Alias\Alias->onDataPacketReceive(object pocketmine\event\server\DataPacketReceiveEvent)
07.04 15:38:44 [Server] Server thread/CRITICAL #13 pmsrc/src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object JavierLeon9966\Alias\Alias, object pocketmine\event\server\DataPacketReceiveEvent)
07.04 15:38:44 [Server] Server thread/CRITICAL #14 pmsrc/src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketReceiveEvent)
07.04 15:38:44 [Server] Server thread/CRITICAL #15 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(108): pocketmine\event\Event->call()
07.04 15:38:44 [Server] Server thread/CRITICAL #16 pmsrc/src/pocketmine/network/mcpe/protocol/BatchPacket(130): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\LoginPacket)
07.04 15:38:44 [Server] Server thread/CRITICAL #17 pmsrc/src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(109): pocketmine\network\mcpe\protocol\BatchPacket->handle(object pocketmine\network\mcpe\PlayerNetworkSessionAdapter)
07.04 15:38:44 [Server] Server thread/CRITICAL #18 pmsrc/src/pocketmine/Player(3318): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
07.04 15:38:44 [Server] Server thread/CRITICAL #19 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(169): pocketmine\Player->handleDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket)
07.04 15:38:44 [Server] Server thread/CRITICAL #20 pmsrc/vendor/pocketmine/raklib/src/server/ServerHandler(95): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string[17] 81.0.39.220 21330, object raklib\protocol\EncapsulatedPacket, integer 0)
07.04 15:38:44 [Server] Server thread/CRITICAL #21 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(109): raklib\server\ServerHandler->handlePacket()
07.04 15:38:44 [Server] Server thread/CRITICAL #22 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(99): pocketmine\network\mcpe\RakLibInterface->process()
07.04 15:38:44 [Server] Server thread/CRITICAL #23 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(113): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}()
07.04 15:38:44 [Server] Server thread/CRITICAL #24 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(75): pocketmine\snooze\SleeperHandler->processNotifications()
07.04 15:38:44 [Server] Server thread/CRITICAL #25 pmsrc/src/pocketmine/Server(2155): pocketmine\snooze\SleeperHandler->sleepUntil(double 1617809924.082)
07.04 15:38:44 [Server] Server thread/CRITICAL #26 pmsrc/src/pocketmine/Server(1992): pocketmine\Server->tickProcessor()
07.04 15:38:44 [Server] Server thread/CRITICAL #27 pmsrc/src/pocketmine/Server(1586): pocketmine\Server->start()
07.04 15:38:44 [Server] Server thread/CRITICAL #28 pmsrc/src/pocketmine/PocketMine(291): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[48] /, string[56] /plugins/)
07.04 15:38:44 [Server] Server thread/CRITICAL #29 pmsrc/src/pocketmine/PocketMine(321): pocketmine\server()
07.04 15:38:44 [Server] Server thread/CRITICAL #30 pmsrc(11): require(string[108] phar:///PMMP-Latest-Stable.phar/s)

(Alias Lat Ver)
(libasynql dev 137)

**Comment by JavierLeon9966** [comment]
Fixed at 1.0.2
